baseURL: http://opendata.atlas.cern/
languageCode: en-us
title: ATLAS Open Data
theme: hugo-refresh
# theme: ../..

#########################################
######## Uncomment this option ##########
#########################################
# This options specify where to look for the images used in this config
# The default value is the "asset" directory of this theme
# assetDir: "static"

# Option to specify the default language of the theme
# I.e., the landing language of your root
DefaultContentLanguage: en

## Option to disable additional language in your site.
# disableLanguages: ["ru"]

disableKinds: ["sitemap","RSS"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parameter used to specify the number of article in each row
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 2

  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/opendata.svg"

  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: true
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: true
  # option to specify the main colour of the theme
  mainColour: "#0b80c3"

  # summary options
  summary:
    # option to specify the default image in the summary list
    # the starting folder is configure in "assetDir" of this file
    defaultImage : "/images/default_summary.jpg"

  # loading options
  loading:
    # option to specify the loading image
    # the starting folder is configure in "assetDir" of this file
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Ubuntu"

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/opendata.svg"
    # option to specify the font of the sidebar
    fontFamily: "Ubuntu" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the logo of the sidebar
    fontFamily: "Ubuntu"

  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    # the starting folder is configure in "assetDir" of this file
    image: "images/ATLAS-logo_404.gif"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 600px

  # homepage options
  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be: "none", "menu", "footer" or "menu+footer"
    linkPosition: "menu+footer"
    # this options let you specify the text of the link to the homepage
    # linkText: "Home"
    # option to specify the title in the homepage
    title: ATLAS Open Data
    # option to specify the subtitle in the homepage
    subtitle: An Educational project in High Energy Physics
    # option to specify image in the homepage
    image: "images/ATLAS-logo.gif" #ATLASOD.gif # worker.svg
    # option to specify the width of the image in the homepage
    imageWidth: 200%

  # footer options
  footer:
    # option to specify the logo in the footer
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/opendata.svg"
    # option to specify your contact email in the footer
    email:
      link: atlas.outreach.data.tools@cern.ch
      title: Contact
    # option to specify your linkedin profile in the footer
    #linkedin:
    #  link: https://atlas.cern/resources/opendata
    #  title: ATLAS public site
    # option to specify your facebook account in the footer;
    # **uncomment** the lines below to show in footer
    # facebook:
    #   link: your.username
    #   title: Facebook
    # option to specify your github account in the footer;
    # **uncomment** the below lines to show in footer
    github:
      link: atlas-outreach-data-tools
      title: Github
    # option to specify your twitter username in the footer;
    # **uncomment** the below lines to show in footer
    # twitter:
    #    link: username
    #    title: Twitter
    # option to specify your instagram username in the footer;
    # **uncomment** the below lines to show in footer
    # instagram:
    #   link: atlasexperiment
    #   title: ATLAS Instagram
    # option to specify the copyright in the footer
    copyright: Website by ATLAS @CERN - 2020

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  en:
    languageName:       English
    weight:             1
  ru:
    languageName:       Russian
    weight:             2
    # When Specifying different parameters for a different language
    # you need to specify all the mandatory sub-parameters as well.
    # E.g.: if you specify the "homepage" parameter then you need to
    #       specify all mandatory sub-parameters, e.g.: "title".
    # See example below:
    params:
      homepage:
        title: ATLAS Open Data
        subtitle: Персональный сайт и блог
        image: "images/ATLAS-logo.gif" #ATLASOD.gif # worker.svg
        imageWidth: 600px

      # Some sub-parameters of the "footer" parameter
      # can be omitted because the code allows for them to be
      # missed but they will treated as they do not exist,
      # i.e., the parameters of the default language
      # won't be inherited.
      footer:
        logo: "/images/opendata.svg"
        email:
          link: имя.фамилия@домен.com
          title: Эл. адрес
        # linkedin:
        #   link: your_linkedin_profile
        #   title: LinkedIn
        # facebook:
        #   link: your.username
        #   title: Facebook
        # twitter:
        #   link: username
        #   title: Twitter
        # instagram:
        #   link: username
        #   title: Instagram
        # github:
        #   link: username
        #   title: Github
        copyright: ATLAS @CERN - 2020
